name: Go

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        go:
        - 1.15.x
        - 1.16.x
        - 1.17.x
        - 1.18.x
        - 1.19.x

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Download Dependencies
      run: go mod download

    - name: Test
      run: make test
